### ISSUE TITLE
PipeDream: Generalized Pipeline Parallelism for DNN Training

### ISSUE THREAD

**Issue by junjunjunk** [junjunjunk/survey-paper#7]
https://www.pdl.cmu.edu/PDL-FTP/BigLearning/sosp19-final271.pdf

https://github.com/msr-fiddle/pipedream

**Comment by junjunjunk** [comment]
setup.shはdockerコンテナ環境を用意するためのスクリプト

**Comment by junjunjunk** [comment]
localでdockerImageを取得
それをscpでreedbushアカウントのworkディレクトリ下に送信
singularityでロード

**Comment by junjunjunk** [comment]
~~https://qiita.com/manabuishiirb/items/c72f3d8e7b82d7a1f5b2
docker saveではなくdocker exportを使う。
がプライベートから持ってくる権限はなさそう。~~

うまくいかなかったのでdocker hubのプライベートリポジトリにイメージファイルをあげる。
キャッシュパスを指定してsingularityでhubから持ってくる。
singularity build <save_name> <reference>

**Comment by junjunjunk** [comment]
ModuleNotFoundError: No module named 'graphviz'と言われた（コンテナ内）ので
conda install graphviz
pip install --user graphviz
で動いた。

**Comment by junjunjunk** [comment]
imagenet_downloadが時間がかかりすぎて見張ってないとインタラクティブではkillされる
これはscreenを使うかscp/rsyncで解決する。

**Comment by junjunjunk** [comment]
reedbushにはscreenが無い？

**Comment by junjunjunk** [comment]
ローカルでscreenでdownload_imagenet.pyを動かす。それをscp/rsyncで送信。

**Comment by junjunjunk** [comment]
バッチスクリプトを飛ばすと何故かモジュールがインポートできない。

Traceback (most recent call last):
  File "./pipedream/profiler/image_classification/main.py", line 5, in <module>
    import torchmodules.torchgraph as torchgraph
ModuleNotFoundError: No module named 'torchmodules'

**Comment by junjunjunk** [comment]
sys.path にモジュールのあるパスを追加するとインポートできる
https://chaika.hatenablog.com/entry/2018/08/24/090000

**Comment by junjunjunk** [comment]
バッチジョブだと何故か相対パスだと死ぬので絶対パスで指定。

**Comment by junjunjunk** [comment]
Traceback (most recent call last):
  File "./pipedream/profiler/image_classification/main.py", line 7, in <module>
    import torchmodules.torchgraph as torchgraph
  File "/lustre/gk43/k43004/pipedream/profiler/torchmodules/torchgraph/__init__.py", line 4, in <module>
    from .graph_creator import cat, GraphCreator, TensorWrapper
  File "/lustre/gk43/k43004/pipedream/profiler/torchmodules/torchgraph/graph_creator.py", line 16, in <module>
    import graph
  File "/lustre/gk43/k43004/pipedream/graph/__init__.py", line 4, in <module>
    from .graph import Graph, Node
  File "/lustre/gk43/k43004/pipedream/graph/graph.py", line 4, in <module>
    import graphviz
ModuleNotFoundError: No module named 'graphviz'

**Comment by junjunjunk** [comment]
graphvizが無いと言われるのでgraph.pyで無理やりパスを追加。
pathはpip show graphvizでみれる

**Comment by junjunjunk** [comment]
.localフォルダがコンテナ立ち上げると中身が変わっちゃう？のでhttps://qiita.com/ronin_gw/items/cdf8112b61649ca455f5

**Comment by junjunjunk** [comment]
profilerを動かすには別のコンテナを用意しないといけないっぽい？
ビルド中

**Comment by junjunjunk** [comment]
singularityの仕様がよくわかってない、shellとexecでパスが違ってたりする

**Comment by junjunjunk** [comment]
Purpose : "メモリ占有量を制限した中で最高のパフォーマンスを出せるようにする"
メモリ占有量を制限することでより早い探索などにも繋がる。
現状の様々な論文はワークロードバランスが等しくなることなどを意識して、メモリ容量そのものを考慮して最適化を行うわけではない。それによりメモリ消費量はそれぞれで小さくはなるが…

**Comment by junjunjunk** [comment]
だからと言ってmodel parallelismをしまくればメモリ消費量は下がるが学習時間が遅くなりすぎる。
その間をピックする。

**Comment by junjunjunk** [comment]
結局動かず。dockerfileのビルドもうまくいかない。
一応AWSのEC2に環境がそのままあるらしいが
